### ISSUE TITLE
ID_0001 > UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error

### ISSUE THREAD

**Issue by diegomrz** [diegomrz/rocketseat-gostack-gobarber#4]
**Erro de validação do sequelize**

UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error

`[nodemon] starting node -r sucrase/register src/server.js
Executing (default): INSERT INTO "users" ("id","name","email","password_hash","created_at","updated_at") VALUES (DEFAULT,$1,$2,$3,$4,$5) RETURNING *;
(node:23080) UnhandledPromiseRejectionWarning: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\sequelize\lib\dialects\postgres\query.js:324:18)
    at C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\rel    at Immediate.Async.drainQueues [as _onImmediate] (C:\DiegoMartinez\GitHubRepositories\rocketseat-gostack-gobarber\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
(node:23080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by diegomrz** [comment]
HOT FIX ID_0001

https://github.com/diegomrz/rocketseat-gostack-gobarber/commit/c61a6179ad7563fdeebfc72552b5eae4d37804cd
